version: '3.8'

services:
  api:
    container_name: clean_go_api
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app/
    ports:
      - "${API_PORT:-8080}:8080"
    env_file:
      - ./.env.dev
    networks:
      - local_network
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: gorm_postgres
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - local_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  local_network:
    driver: bridge


volumes:
    postgres: